config/routes.rb
Rails.application.routes.draw do

    root 'home#index'
      
    get 'password_resets/new'
  
    get 'password_resets/edit'
  
    get 'sessions/new'
  
    get 'users/new'

  
  
    get 'frequently_asked_questions' => 'static_pages#frequently_asked_questions'
  
  
    get 'about' =>  'static_pages#about'
    get 'jobs' =>  'static_pages#jobs'
    get 'community' =>  'static_pages#community'
    
    
    get 'doctor_job' => 'job_postings#doctor_job'
    get 'software_intern' => 'job_postings#software_intern'
    get 'web_dev' => 'job_postings#web_dev'
    
    get 'michael' => 'static_pages#michael'
    get 'francis' => 'static_pages#francis'
    get 'vance' => 'static_pages#vance'
    get 'thuan' => 'static_pages#thuan'
    
  
    get 'contact' => 'static_pages#contact'
  
    get 'help'    => 'static_pages#help'
  
    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    post 'pusher/auth'
   
    resources :users do
      member do
        post 'reactivate'
      end
      collection do
        get 'favorites'
      end
    end
    resources :doctors, only: :index do
      collection do
        get 'favorite'
      end
    end
    resources :sessions
    resources :video_sessions do
      member do
        get 'edit/feedback', to: 'video_sessions#feedback'
        get 'edit/notes', to: 'video_sessions#notes'
        patch 'finish', to: 'video_sessions#finish'
        patch 'update/feedback', to: 'video_sessions#update_feedback'
        patch 'update/notes', to: 'video_sessions#update_notes'
        patch 'update/add_diagnosis', to: 'video_sessions#add_diagnosis'
        patch 'update/sign_off', to: 'video_sessions#sign_off'
        patch 'update/save', to: 'video_sessions#save'
        get 'export'
        post 'transfer'
        post 'wait'

        resources :call_backs, only: [:new, :create]
        resources :online_visits, only: [:new, :create]
        resources :messages, only: [:new, :create]
        
      end
    end
    resources :call_backs, only: [:edit, :update, :destroy, :show, :create]
    
    resources :online_visits, only: [:edit, :update, :destroy, :show]
    resources :messages, only: [:show, :index, :update] do
      member do
        resources :answers, only: [:create]
      end
    end
    resources :photos, only: :create
    resources :history_video_sessions, only: [:index, :show]
    resources :clinics do
      collection do
        get 'favorite'
      end
    end
    resources :favorite_clinics, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :favorite_doctors, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :appointments do
      member do
        post 'cancel'
      end
    end
    resources :not_working_dates, only: [:new, :create, :destroy]

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tasks
    resources :working_schedules, only: [:index]
    
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

    namespace :api do
      namespace :v1 do
        resources :users, only: [:create, :update] do
          collection do
            post 'sign_in' => 'sessions#create'
          end
        end
        resources :video_sessions do
          member do
            resource :opentok_session, only: :show
            post 'cancel'
          end
        end
        resources :appointments
        resources :clinics
        resources :doctors
        resources :messages
        resources :call_backs
      end
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def about
  end

  def contact
  end

  def help
  end

  def signup
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, t('content.about')) %>


        <div class="breadcrumbs-v3 img-v3 text-center ">
            <div class="container">
                <h1><%= t('content.about')%></h1>
                <p><strong>247Clinic.ca is simple and easy to use</strong></p>
            </div>
        </div>
        <br>
        <div class="container content-sm">
            
                <p class="no-margin-bottom">247clinic.ca aims to streamline health care with technology in the most efficient way possible.
                Using web enabled cameras and video streaming technology, we want to bring together patients and doctors online to reduce wait 
                times and unnecessary visits to doctors office. Our goal is to connect physicians and patients by providing an easily accessible online 
                platform that is available through their smart devices (Android and iOS) and/or Web browser; resulting in a safe and reliable yet time saving 
                approach to connect you with the help you need.</p>
                
                <p  class="no-margin-bottom">Our company started with just a simple idea of bringing health care to everyone with ease. We then take this idea and further expanded our passion to not only bringing patients 
                and doctors together, but also to connect any health provider to any client. We are working to expand further to all sorts of people who need our services.</p>
               <br>
               <br>
               <div class="title-v1 no-margin-bottom">
               <%= link_to 'Contact Us',   contact_path, :class=>"btn-u btn-brd-hover btn-u-dark" %>
                <%= link_to 'Book Appointment Now',   new_appointment_path, :class=>"btn-u btn-brd-hover btn-u-dark" %>
                
            </div>
        </div>
        <div class="service-block-v4">
            <div class="container content-sm">
                <div class="row">
                    <div class="col-md-4 service-desc md-margin-bottom-20">
                        <i class="icon-diamond"></i>
                        <h3>Goal</h3>
                        <p class="no-margin-bottom"> Our goal is to connect doctors and patients without the hassle of waiting in line. Fast, easy, and simple. </p>
                    </div>
                    <div class="col-md-4 service-desc md-margin-bottom-20">
                        <i class="icon-rocket"></i>
                        <h3>Development</h3>
                        <p class="no-margin-bottom">247Clinic is always looking to expand its scope to encompass any and all needs of our clients. If you have any suggestions please let us know! </p>
                    </div>
                    <div class="col-md-4 service-desc">
                        <i class="icon-support"></i>
                        <h3>Support</h3>
                        <p class="no-margin-bottom">If you have any questions please feel free to e-mail us at info@clinic.ca. Alternatively you can call us at 1-888-808-8168 </p>
                    </div>
                </div><!--/end row-->
            </div><!--/end container-->
        </div>         

app/views/static_pages/community.html.erb
<% provide(:title, t('content.community')) %>
 <!--=== Breadcrumbs v3 ===-->
    <div class="breadcrumbs-v3 img-v1 margin-bottom-60">
        <div class="container text-center">
            <p>Meet Our Folks</p>
            <h1>Our Professional Team Members</h1>
        </div><!--/end container-->
    </div>
    <!--=== End Breadcrumbs v3 ===-->

   <!--=== Team v5 ===-->
    <div class="container">
        <div class="headline-center margin-bottom-60">
            <h2>TEAM MEMBERS</h2>
            <p>Our team of highly determined and self-motivated individuals 
           
        </div>

        <div class="row team-v5 margin-bottom-30">
            <div class="col-sm-4">
                <div class="team-img">
                     <%= image_tag 'VanceHeadShotcrop.jpg', size: "height:270;width:auto;" %>
                    <div class="team-hover">
                    </div>
                </div>
                <span> <%= link_to 'Vance Licaros',   vance_path %> </span>
                <small>Chief Technology Officer</small>
                <p>"It is better to have loved and lost, than never to have loved at all."</p>
            </div>
            
            <div class="col-sm-4">
                <div class="team-img">
                     <%= image_tag 'MichaelQ.jpg', size: "height:360;width:auto;" %>
                    <div class="team-hover">
                    </div>
                </div>
                <span> <%= link_to 'Michael JunHao Qiu',   michael_path %> </span>
                <small>Chief Medical Officer</small>
               <p>"To you it is given to know the secrets of the Kingdom of God, but for others they are in parables."</p>
            </div>
            <div class="col-sm-4 sm-margin-bottom-50">
                <div class="team-img">
                     <%= image_tag 'thuanPham.jpg', size: "height:270;width:auto;" %>
                    <div class="team-hover">
                    </div>
                </div>
                <span> <%= link_to 'Thuan Pham',   thuan_path %> </span>
                <small>Web Developer</small>
                <p>"Float like a butterfly, sting like a bee."</p>
            </div>
            
            <div class="col-sm-4 sm-margin-bottom-50">
                <div class="team-img">
                     <%= image_tag '10329705_1014594918634956_3814649206592667887_o.jpg', size: "height:270;width:auto;" %>
                    <div class="team-hover">
                    </div>
                </div>
                <span> <%= link_to 'Francis Tran',   francis_path %> </span>
                <small>Software Intern</small>
                <p>"Always mind your surroundings."</p>
            </div>
            
        </div><!--/end team v5-->
    </div>

app/views/static_pages/contact.html.erb
<% provide(:title,  t('content.contact')) %>

    <!--=== Content Part ===-->
    <div class="container content">
    	<div class="row margin-bottom-30">
    		<div class="col-md-9 mb-margin-bottom-30">
                <div class="headline"><h2><%= t('content.contact')%></h2></div>
               <p>Contact us:</p>
                <p>Phone: 1-888-808-8168</p>
                <p>Email: info@247clinic.ca</p>
                <p>Our Office is located in the Greater Lower Vancouver Area</p>
               <br />

    			
            </div><!--/col-md-9-->

    		<div class="col-md-3">
            	<!-- Contacts -->
                <div class="headline"><h2>Contact Information</h2></div>
                <ul class="list-unstyled who margin-bottom-30">
                    <li><a href="#"><i class="fa fa-home"></i>1615 10th Ave SW Unit 206B</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i>info@247clinic.ca</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i>1 888 808 8168</a></li>
                </ul>

            

            	<!-- Why we are? -->
               
            </div><!--/col-md-3-->
        </div><!--/row-->

       
    </div><!--/container-->
    <!--=== End Content Part ===-->

app/views/static_pages/francis.html.erb
<% provide(:title, t('content.francis')) %>

   

<body>
<div class="wrapper">
    

    <!--=== Team v5 ===-->
    <div class="container">
        <div class="headline-center margin-bottom-1">
        </div>

        <div class="row team-v5 margin-bottom-30">
            
            
            <div class="col-sm-3">
                <div class="team-img">
                    <%= image_tag '10329705_1014594918634956_3814649206592667887_o.jpg', size: "16x300" %>
                </div>
            </div>
                <h3 align="left"> Francis Tran </h3>
                <h6 align="left">Software Intern</h6>
                <hr style="height:1px; border:none; color:#808080; background-color:#808080;" />
               <p align = "left">Francis Tran is a 3rd year undergrad student studying Engineering Science at SFU with a concentration in Electronics Engineering. Although devoted to 
                               his job, his other interests include hiking, skating, skiing and snowboarding, and anything outdoors related.</p>
            </div>
        </div><!--/end team v5-->
    </div>
    <!--=== End Team v5 ===-->

    <hr class="margin-bottom-10">

    <!--=== Team v6 ===-->


   
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->



</body>

app/views/static_pages/help.html.erb
<% provide(:title, t('content.help')) %>
<!DOCTYPE html>
<h1><%= t('content.help') %></h1>
<p>How can we help you? "Get help now!"</p>
<p>Need immediate assistance please contact your Family physician.</p>
<p>In case of an emergency please call 911</p>
<p>For other general inquiry try our toll free line: 1-800-123-4567</p>

<p>
  For more personal help please check-out our leading member Francis Tran personal page:
  <a href="https://www.facebook.com/francis.tran.967?fref=ts">(Junior Advisor)</a>
</p>

app/views/static_pages/jobs.html.erb
<% provide(:title, "Jobs") %>
  <div class="container content-sm">
    <!--=== Job Img ===-->
    <div class="job-img margin-bottom-2">
        <div class="job-banner">
            <h2>Find the perfect fit to start your career!</h2>
            <p>We are currently looking for directors, enthusiastic web-developers and more to join our team.</p>
            <p>There are currently positions for health praticioners to offer the expertise others.</p>
        </div>
        
    </div>
    <!--=== End Job Img ===-->
</div>
    <!--=== Content Part ===-->
    <div class="container content">
        <!-- Begin Service Block -->
        <div class="row margin-bottom-10">
            <div class="col-md-60 col-sm-60">
                <div class="service-block service-block-sea service-or">
                    <div class="service-bg"></div>
                    <i class="icon-custom icon-color-light rounded-x fa fa-lightbulb-o"></i>
                    <h2 class="heading-md">Why work for us?</h2>
                    <p>We are a tight-knit group that can provide flexible hours and dynamic relationships. </p>
                    <p>Here at 247Clinic we will take the time to help train and equip you with 
                    skills to help you reach your maximum potential</p>
                </div>
            </div>
          
        </div>
        <!-- End Begin Service Block -->

app/views/static_pages/michael.html.erb
<% provide(:title, t('content.michael;')) %>

   
<body>
<div class="wrapper">
    

    <!--=== Team v5 ===-->
    <div class="container">
        <div class="headline-center margin-bottom-1">
        </div>

        <div class="row team-v5 margin-bottom-30">
            
            
            <div class="col-sm-3">
                <div class="team-img">
                    <%= image_tag 'MichaelQ.jpg', size: "16x300"  %>
                </div>
            </div>
                <h3 align="left"> Michael JunHao Qiu </h3>
                <h6 align="left">Medical Practitioner</h6>
                <hr style="height:1px; border:none; color:#808080; background-color:#808080;" />
               <p align = "left">Michael Junhao Qiu is a Canadian student studying medicine at the University of Edinburgh. 
               He obtained a Bachelor of Science (Hons) from the University of St. Andrew's Faculty of Medicine prior to his clinical training. 
               Michael is a medical board member of Health Choices First, an advanced North American medical directory & video site, featuring more than 1,500 
               health and lifestyle videos. He is the founder and current chair of the Association of Medical Opportunities for Canadians, an organization that provides 
               undergraduates and medical students with observership and elective experiences. Michael has a strong interest in eHealth and the the Electronic Medical 
               Record (EMR) systems. Whilst working under his mentors, many of his projects have sparked the interest of telehealth and pharmaceutical companies. He has 
               successfully authored several scientific poster publications and presented at international conferences. </p>
            </div>
        </div><!--/end team v5-->
    </div>
    <!--=== End Team v5 ===-->

    <hr class="margin-bottom-10">

    <!--=== Team v6 ===-->


   
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->


</body>

app/views/static_pages/signup.html.erb
<% provide(:title, t('title.signup')) %>
<h1>StaticPages#signup</h1>
<p>Find me in app/views/static_pages/signup.html.erb</p>

app/views/static_pages/thuan.html.erb
<% provide(:title, t('content.thuan')) %>

    
<body>
<div class="wrapper">
    

    <!--=== Team v5 ===-->
    <div class="container">
        <div class="headline-center margin-bottom-1">
        </div>

        <div class="row team-v5 margin-bottom-30">
            
            
            <div class="col-sm-3">
                <div class="team-img">
                    <%= image_tag 'thuanPham.jpg', size: "16x300" %>
                </div>
            </div>
                <h3 align="left"> Thuan Pham B. Sc</h3>
                <h6 align="left">Web Developer</h6>
                <hr style="height:1px; border:none; color:#808080; background-color:#808080;" />
               <p align = "left">Thuan Pham is a graduate from SFU with a degree in Mathematics.</p>
            </div>
        </div><!--/end team v5-->
    </div>
    <!--=== End Team v5 ===-->

    <hr class="margin-bottom-10">

    <!--=== Team v6 ===-->


   
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->



</body>

app/views/static_pages/vance.html.erb
<% provide(:title, t('content.jobs')) %>

    <!--=== Team v5 ===-->
    <div class="container">
        <div class="headline-center margin-bottom-1">
        </div>

        <div class="row team-v5 margin-bottom-30">
            
            
            <div class="col-sm-3">
                <div class="team-img">
                    <%= image_tag 'VanceHeadShotcrop.jpg', size: "16x300"  %>
                </div>
            </div>
                <h3 align="left"> Vance Licaros B. A Sc </h3>
                <h6 align="left">Chief Technology Officer</h6>
                <hr style="height:1px; border:none; color:#808080; background-color:#808080;" />
               <p align = "left">"It is better to have loved and lost, than never to have loved at all" </p>
            </div>
        </div><!--/end team v5-->
    </div>
    <!--=== End Team v5 ===-->

    <hr class="margin-bottom-10">

    <!--=== Team v6 ===-->