config/routes.rb
Rails.application.routes.draw do

    root 'home#index'
      
    get 'password_resets/new'
  
    get 'password_resets/edit'
  
    get 'sessions/new'
  
    get 'users/new'

  
  
    get 'frequently_asked_questions' => 'static_pages#frequently_asked_questions'
  
  
    get 'about' =>  'static_pages#about'
    get 'jobs' =>  'static_pages#jobs'
    get 'community' =>  'static_pages#community'
    
    
    get 'doctor_job' => 'job_postings#doctor_job'
    get 'software_intern' => 'job_postings#software_intern'
    get 'web_dev' => 'job_postings#web_dev'
    
    get 'michael' => 'static_pages#michael'
    get 'francis' => 'static_pages#francis'
    get 'vance' => 'static_pages#vance'
    get 'thuan' => 'static_pages#thuan'
    
  
    get 'contact' => 'static_pages#contact'
  
    get 'help'    => 'static_pages#help'
  
    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    post 'pusher/auth'
   
    resources :users do
      member do
        post 'reactivate'
      end
      collection do
        get 'favorites'
      end
    end
    resources :doctors, only: :index do
      collection do
        get 'favorite'
      end
    end
    resources :sessions
    resources :video_sessions do
      member do
        get 'edit/feedback', to: 'video_sessions#feedback'
        get 'edit/notes', to: 'video_sessions#notes'
        patch 'finish', to: 'video_sessions#finish'
        patch 'update/feedback', to: 'video_sessions#update_feedback'
        patch 'update/notes', to: 'video_sessions#update_notes'
        patch 'update/add_diagnosis', to: 'video_sessions#add_diagnosis'
        patch 'update/sign_off', to: 'video_sessions#sign_off'
        patch 'update/save', to: 'video_sessions#save'
        get 'export'
        post 'transfer'
        post 'wait'

        resources :call_backs, only: [:new, :create]
        resources :online_visits, only: [:new, :create]
        resources :messages, only: [:new, :create]
        
      end
    end
    resources :call_backs, only: [:edit, :update, :destroy, :show, :create]
    
    resources :online_visits, only: [:edit, :update, :destroy, :show]
    resources :messages, only: [:show, :index, :update] do
      member do
        resources :answers, only: [:create]
      end
    end
    resources :photos, only: :create
    resources :history_video_sessions, only: [:index, :show]
    resources :clinics do
      collection do
        get 'favorite'
      end
    end
    resources :favorite_clinics, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :favorite_doctors, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :appointments do
      member do
        post 'cancel'
      end
    end
    resources :not_working_dates, only: [:new, :create, :destroy]

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tasks
    resources :working_schedules, only: [:index]
    
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

    namespace :api do
      namespace :v1 do
        resources :users, only: [:create, :update] do
          collection do
            post 'sign_in' => 'sessions#create'
          end
        end
        resources :video_sessions do
          member do
            resource :opentok_session, only: :show
            post 'cancel'
          end
        end
        resources :appointments
        resources :clinics
        resources :doctors
        resources :messages
        resources :call_backs
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token, :password_confirmation
  before_save :downcase_email
  before_save :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :video_sessions, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :favorite_clinics, dependent: :destroy
  has_many :favorite_doctors, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :not_working_dates, dependent: :destroy
  has_many :working_schedules
  accepts_nested_attributes_for :working_schedules, reject_if: :all_blank, allow_destroy: true

  belongs_to :clinic

  after_create :generate_authentication_token!

  def generate_authentication_token!
    self.authentication_token = Digest::SHA1.hexdigest("#{Time.now}-#{self.id}-#{self.updated_at}")
    self.save
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
   
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def doctor?
    user_type == 'doctor'
  end

  def patient?
    user_type == 'patient'
  end

  def csr?
    user_type == 'csr'
  end

  def user_type_string
    self.admin? ? 'Admin' : (self.user_type.try(:capitalize) || 'Patient')
  end


  def not_working_days
    if read_attribute(:not_working_days).is_a?(String)
      read_attribute(:not_working_days).split(',')
    else
      super
    end
  end

  def not_working_days=(val)
    if val.is_a?(Array)
      self.not_working_days = val.join(',')
    else
      super
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end  

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
    # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::AuthenticateController
  skip_before_action :authenticate, only: :create
  before_action :set_user, only: [:update]

  def update
    if @user.update(user_update_params)
      render json: @user
    else
      render json: @user.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user
    else
      render json: @user.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone, :mspnum, :birthdate, :password, :password_confirmation)
    end

    def user_update_params
      params.require(:user).permit(:name, :email, :phone, :mspnum, :birthdate, :password, :password_confirmation, :user_type, :clinic_id, not_working_days:[])
    end

    def set_user
      @user = User.find_by(id: params[:id])
      render json: { result: 'fail' } if @user.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :reactivate]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy, :show, :reactivate]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @not_working_days = Date::DAYNAMES
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @clinic = @user.clinic
    if @clinic.present? and @clinic.not_opening_days
      @not_working_days = Date::DAYNAMES - @clinic.not_opening_days
    else
      @not_working_days = Date::DAYNAMES
    end
  end

  def reactivate
    @user = User.find(params[:id])
    if @user
      if @user.activated?
        flash[:info] = "Already activated."
      elsif @user.save
        @user.send_activation_email
        flash[:info] = "Activation email has been sent."
      end
    end
    redirect_to root_url
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end    
  end

  def favorites
    if current_user.admin? or current_user.doctor?
      redirect_to(root_url)
    else
      @favorite_clinics = current_user.favorite_clinics.order(:clinic_id)
      @favorite_doctors = current_user.favorite_doctors.order(:doctor_id)
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :mspnum, :password, :password_confirmation,
          :address1, :address2, :city, :country, :provincestate, :zipcode, :phone, :gender, :birthdate, :user_type, :clinic_id, working_schedules_attributes:[:id, :_destroy, :weekly, :scheduled_day_of_week, :scheduled_date, :start_time, :end_time])
    end
        # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless (current_user.admin? || current_user?(@user))
    end 
       
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: 'reg-page '}) do |f| %>

  <% if current_page?(signup_path) %>
    <div class='reg-header'>
      <h2><%= t('form_header.signup') %></h2>
      <p>Already Signed Up? Click <%= link_to t('content.login'), login_path %> to login your account.</p>
    </div>
  <% end %>
  <%= render 'shared/error_messages', object: @user %>

  <% if @user.id %>
    <%= f.label :user_type %>
    <div class='form-control form-group'>
      <%= @user.user_type_string %>
    </div>
  <% else %>
    <!--
    <%= f.label :user_type %>
    <%= f.select :user_type, [], {}, {class: 'form-control'} do %>
      <%= content_tag(:option, 'Patient', value: 'patient') %>
      <%= content_tag(:option, 'Doctor', value: 'doctor', selected: @user.doctor?) %>
    <% end %>
    -->
  <% end %>

  <div class="select_clinic_section">
    <div class="form-group">
      <%= f.label :clinic %>
      <%= f.select :clinic_id,
                   Clinic.all.map { |clinic| [clinic.name, clinic.id] },
                   { include_blank: true },
                   { class: 'form-control' }
      %>
    </div>
    <div class="form-group">
      <%= f.label :working_schedule %>
      <div class="working-schedules">
        <%= f.fields_for :working_schedules do |working_schedule| %>
          <%= render 'working_schedule_fields', f: working_schedule %>
        <% end %>
        <div class="links center">
          <%= link_to_add_association 'Add', f, :working_schedules, class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  </div>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :phone %>
  <%= f.telephone_field :phone, class: 'form-control' %>

  <%= f.label :mspnum %>
  <%= f.text_field :mspnum, class: 'form-control' %>

  <div class="form-group">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, class: 'form-control' %>
  </div>
<!--
  <%= f.label :address1 %>
  <%= f.text_field :address1, class: 'form-control' %>
  <%= f.label :address2 %>
  <%= f.text_field :address2, class: 'form-control' %>
  <%= f.label :city %>
  <%= f.select :city, [], {}, class: 'form-control' do %>
    <% [['Vancouver', 1], ['Richmond', 2], ['Burnaby', 3], ['Surrey', 4], ['North Vancouver', 5]].each do |c| -%>
      <%= content_tag(:option, c.first, value: c.last) %>
    <% end %>
  <% end %>
  <%= f.label :country %>
  <%= f.text_field :country, class: 'form-control' %>
  <%= f.label :provincestate %>
  <%= f.text_field :provincestate, class: 'form-control' %>
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode, class: 'form-control' %>
  <%= f.label :gender %>
  <%= f.text_field :gender, class: 'form-control' %>
  <%= f.label :birthdate %>
  <%= f.date_select :birthdate, class: 'form-control' %>
-->
  <div class="row margin-top-20">
    <div class="col-sm-6">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="col-sm-6">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-6 text-right">
      <%= f.button class: "btn-u" %>
    </div>
  </div>
<% end %>

<%= javascript_tag do %>
  $('.input-group').datetimepicker();
  $('.chosen-select').chosen({no_results_text: 'No results matched'});
  init_clinic_section('<%= @user.user_type %>');
  init_working_schedule_fields();
<% end %>

app/views/users/_form_simple.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :user_type %>
  <%= f.select :user_type, class: 'form-control' do %>
    <%= content_tag(:option, 'Patient', value: 'patient') %>
    <%= content_tag(:option, 'Doctor', value: 'doctor', selected: @user.doctor?) %>
    <%= content_tag(:option, 'CSR', value: 'csr', selected: @user.csr?) %>
  <% end %>

  <div class="select_clinic_section">
    <%= f.label :clinic %>
    <%= f.select :clinic_id,
                 Clinic.all.map { |clinic| [clinic.name, clinic.id] },
                 { include_blank: true }
    %>
  </div>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  init_clinic_section('<%= @user.user_type %>');
</script>

app/views/users/_user.html.erb
<tr>
  <td><%= gravatar_for user, size: 50 %></td>
  <td><%= link_to user.name, user %></td>
  <td><%= user.user_type_string %></td>
  <% if current_user.admin? && !current_user?(user) %>
    <td><%= link_to "Change Profile", edit_user_path(user) %></td>
    <td><%= link_to "Reset Password", { controller: 'password_resets', action: 'create', password_reset: { email: user.email }}, method: :post %></td>
    <td><%= link_to "Reactivation", { controller: 'users', action: 'reactivate', id: user.id }, method: :post %></td>
    <td><%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" } %></td>
  <% else %>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  <% end %>
</tr>

app/views/users/_working_schedule_fields.html.erb
<%= render 'working_schedules/working_schedule_fields', f: f %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% if current_user?(@user) %>
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
<!--
      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank">Change</a>
      </div>
-->
    </div>
  </div>
<% else %>
  <h1>Update profile </h1>
  <h2><%= @user.name %></h2>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form_simple' %>
    </div>
  </div>

<% end %>

app/views/users/favorites.html.erb
<% provide(:title, "Favorites") %>
<h1>Favorite Clinics</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <% if @favorite_clinics.count > 0 %>
      <table class="table">
        <tr>
          <th>No</th>
          <th>Name</th>
        </tr>
        <% @favorite_clinics.each do |favorite_clinic| %>
          <tr>
            <td><%= favorite_clinic.clinic.id %></td>
            <td><%= favorite_clinic.clinic.name %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="text-center form-group">No favorite clinics.</div>
    <% end %>
    <div class="form-group text-center">
      <%= link_to 'Edit favorite clinics', favorite_clinics_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<h1>Favorite Doctors</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <% if @favorite_doctors.count > 0 %>
      <table class="table">
        <tr>
          <th>No</th>
          <th>Name</th>
        </tr>
        <% @favorite_doctors.each do |favorite_doctor| %>
          <tr>
            <td><%= favorite_doctor.doctor.id %></td>
            <td><%= favorite_doctor.doctor.name %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="text-center form-group">No favorite doctors.</div>
    <% end %>
    <div class="form-group text-center">
      <%= link_to 'Edit favorite doctors', favorite_doctors_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<table class="table">
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </tr>
</table>

<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, t('title.signup')) %>
<% provide(:button_text, 'Create my account') %>

<% unless current_page?(signup_path) %>
  <h1><%= t('title.signup') %></h1>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <%= render 'form'  %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
      </h1>
      <div class="form-group">
        <%= @user.name %>
      </div>
      <label><%= @user.user_type_string %></label>
    </section>
  </aside>
</div>