config/routes.rb
Rails.application.routes.draw do

    root 'home#index'
      
    get 'password_resets/new'
  
    get 'password_resets/edit'
  
    get 'sessions/new'
  
    get 'users/new'

  
  
    get 'frequently_asked_questions' => 'static_pages#frequently_asked_questions'
  
  
    get 'about' =>  'static_pages#about'
    get 'jobs' =>  'static_pages#jobs'
    get 'community' =>  'static_pages#community'
    
    
    get 'doctor_job' => 'job_postings#doctor_job'
    get 'software_intern' => 'job_postings#software_intern'
    get 'web_dev' => 'job_postings#web_dev'
    
    get 'michael' => 'static_pages#michael'
    get 'francis' => 'static_pages#francis'
    get 'vance' => 'static_pages#vance'
    get 'thuan' => 'static_pages#thuan'
    
  
    get 'contact' => 'static_pages#contact'
  
    get 'help'    => 'static_pages#help'
  
    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    post 'pusher/auth'
   
    resources :users do
      member do
        post 'reactivate'
      end
      collection do
        get 'favorites'
      end
    end
    resources :doctors, only: :index do
      collection do
        get 'favorite'
      end
    end
    resources :sessions
    resources :video_sessions do
      member do
        get 'edit/feedback', to: 'video_sessions#feedback'
        get 'edit/notes', to: 'video_sessions#notes'
        patch 'finish', to: 'video_sessions#finish'
        patch 'update/feedback', to: 'video_sessions#update_feedback'
        patch 'update/notes', to: 'video_sessions#update_notes'
        patch 'update/add_diagnosis', to: 'video_sessions#add_diagnosis'
        patch 'update/sign_off', to: 'video_sessions#sign_off'
        patch 'update/save', to: 'video_sessions#save'
        get 'export'
        post 'transfer'
        post 'wait'

        resources :call_backs, only: [:new, :create]
        resources :online_visits, only: [:new, :create]
        resources :messages, only: [:new, :create]
        
      end
    end
    resources :call_backs, only: [:edit, :update, :destroy, :show, :create]
    
    resources :online_visits, only: [:edit, :update, :destroy, :show]
    resources :messages, only: [:show, :index, :update] do
      member do
        resources :answers, only: [:create]
      end
    end
    resources :photos, only: :create
    resources :history_video_sessions, only: [:index, :show]
    resources :clinics do
      collection do
        get 'favorite'
      end
    end
    resources :favorite_clinics, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :favorite_doctors, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :appointments do
      member do
        post 'cancel'
      end
    end
    resources :not_working_dates, only: [:new, :create, :destroy]

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tasks
    resources :working_schedules, only: [:index]
    
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

    namespace :api do
      namespace :v1 do
        resources :users, only: [:create, :update] do
          collection do
            post 'sign_in' => 'sessions#create'
          end
        end
        resources :video_sessions do
          member do
            resource :opentok_session, only: :show
            post 'cancel'
          end
        end
        resources :appointments
        resources :clinics
        resources :doctors
        resources :messages
        resources :call_backs
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @call_back = CallBack.where('call_backs.user_id = ? OR call_backs.doctor_id = ?', current_user.id, current_user.id)
                     .where.not(scheduled_time: nil)
                     .joins('LEFT JOIN video_sessions ON call_backs.id = video_sessions.call_back_id')
                     .where("video_sessions.status IS NULL OR (video_sessions.status <> 'finished' AND video_sessions.status <> 'callback')").first
    end
  end
end

app/views/home/_banner.html.erb
<div class="tp-banner-container">
  <div class="tp-banner">
    <ul>
      <li class="revolution-mch-1" data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Slide 1">
        <!-- MAIN IMAGE -->
        <img src="<%= image_path('sliders/4.jpg') %>"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
        <div class="tp-caption revolution-ch1 sft start"
          data-x="center"
          data-hoffset="0"
          data-y="100"
          data-speed="1500"
          data-start="500"
          data-easing="Back.easeInOut"
          data-endeasing="Power1.easeIn"
          data-endspeed="300">
          Welcome to 24-7 Clinic
        </div>
        <!-- LAYER -->
        <div class="tp-caption revolution-ch2 sft"
          data-x="center"
          data-hoffset="0"
          data-y="190"
          data-speed="1400"
          data-start="2000"
          data-easing="Power4.easeOut"
          data-endspeed="300"
          data-endeasing="Power1.easeIn"
          data-captionhidden="off"
          style="z-index: 6">
          Seeking responsive diagnosis <br/>
          from a licensed doctor in British Columbia
        </div>
        <!-- LAYER -->
        <div class="tp-caption sft"
          data-x="center"
          data-hoffset="0"
          data-y="310"
          data-speed="1600"
          data-start="2800"
          data-easing="Power4.easeOut"
          data-endspeed="300"
          data-endeasing="Power1.easeIn"
          data-captionhidden="off"
          style="z-index: 6">
          <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-light">Learn More</a>
          <a href="#" class="btn-u">Our Work</a>
        </div>
      </li>
      <li class="revolution-mch-1" data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
          <!-- MAIN IMAGE -->
          <img src="<%= image_path('sliders/2.jpg') %>"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">

          <div class="tp-caption revolution-ch1 sft start"
              data-x="center"
              data-hoffset="0"
              data-y="100"
              data-speed="1500"
              data-start="500"
              data-easing="Back.easeInOut"
              data-endeasing="Power1.easeIn"
              data-endspeed="300">
              Looking for Qualified Doctors
          </div>

          <!-- LAYER -->
          <div class="tp-caption revolution-ch2 sft"
              data-x="center"
              data-hoffset="0"
              data-y="190"
              data-speed="1400"
              data-start="2000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off"
              style="z-index: 6">
              We provide online clinic bookings<br/>
              if you require face-to-face interaction with a doctor.
          </div>

          <!-- LAYER -->
          <div class="tp-caption sft"
              data-x="center"
              data-hoffset="0"
              data-y="310"
              data-speed="1600"
              data-start="2800"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off"
              style="z-index: 6">
              <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-light">Sign Up</a>
              <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-light">Book an Appointment</a>
          </div>
      </li>
      <li class="revolution-mch-1" data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Slide 3">
          <!-- MAIN IMAGE -->
          <img src="<%= image_path('sliders/3.jpg') %>"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">

          <div class="tp-caption revolution-ch1 sft start"
              data-x="center"
              data-hoffset="0"
              data-y="100"
              data-speed="1500"
              data-start="500"
              data-easing="Back.easeInOut"
              data-endeasing="Power1.easeIn"
              data-endspeed="300">
              Simplifying Doctors Visits
          </div>

          <!-- LAYER -->
          <div class="tp-caption revolution-ch2 sft"
              data-x="center"
              data-hoffset="0"
              data-y="190"
              data-speed="1400"
              data-start="2000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off"
              style="z-index: 6">
              We provide on-demand or scheduled online visits<br/>
              if you require face-to-face interaction with a doctor.
          </div>

          <!-- LAYER -->
          <div class="tp-caption sft"
              data-x="center"
              data-hoffset="0"
              data-y="310"
              data-speed="1600"
              data-start="2800"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off"
              style="z-index: 6">
              <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-light">Learn More</a>
              <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-light">Our Work</a>
          </div>
      </li>
    </ul>
    <div class="tp-bannertimer tp-bottom"></div>
  </div>
</div>

app/views/home/index.html.erb
<% if @call_back %>
  <div class="alert alert-success">
    <% if @call_back.user_id == current_user.id %>
      <p>Doctor <%= @call_back.doctor.name %> has scheduled meeting with you at <%= @call_back.scheduled_time.strftime("%B %-d, %Y %I:%M %P") %>.</p>
    <% else %>
      <p>You have has scheduled meeting with patient <%= @call_back.user.try(:name) %> at <%= @call_back.scheduled_time.strftime("%B %-d, %Y %I:%M %P") %>.</p>
    <% end %>

    <p>Please click <%= link_to 'here', video_sessions_url %> to go to Pending Call Backs page.</p>
  </div>
<% end %>
<% if logged_in? %>
  <div class="center jumbotron">
    <h2>Welcome to 24-7 Online Clinic</h1>
    <h2>
    Welcome to your online clinic where you will receive access to doctors within your city without waiting in line or making an appointment.
    </h2>
    <% if logged_in? %>
      <% if current_user.csr? %>
        <%= link_to video_sessions_path(params: { video_session: {}, online_visit: true }), method: :post, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-camera"></span>&nbsp;Start Online Visit
        <% end %>
      <% elsif !current_user.doctor? %>
        <%= link_to video_sessions_path(params: { video_session: {}, online_visit: true }), method: :post, class: "btn btn-primary start-online-visit" do %>
          <span class="glyphicon glyphicon-camera"></span>&nbsp;Start New Visit
        <% end %>
      <% end %>
    <% else %>
      <%= link_to t('content.signup_now'), signup_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
<% else %>

  <!--=== Slider Block ===-->
  <%= render 'banner' %>

  <!--=== Service Block ===-->
  <div class="container content-sm">
      <div class="row">
          <div class="col-md-4 content-boxes-v6 md-margin-bottom-50">
              <i class="rounded-x icon-link"></i>
              <!--<h1 class="title-v3-md text-uppercase margin-bottom-10">Fully responsive</h1>
              <p>At vero eos et accusato odio dignissimos ducimus qui blanditiis praesentium voluptatum.</p>-->
          </div>
          <div class="col-md-4 content-boxes-v6 md-margin-bottom-50">
              <i class="rounded-x icon-paper-plane"></i>
             <!-- <h2 class="title-v3-md text-uppercase margin-bottom-10">Modern design</h2>
              <p>At vero eos et accusato odio dignissimos ducimus qui blanditiis praesentium voluptatum.</p>-->
          </div>
          <div class="col-md-4 content-boxes-v6">
              <i class="rounded-x icon-refresh"></i>
              <!--<h2 class="title-v3-md text-uppercase margin-bottom-10">Powerful slides</h2>
              <p>At vero eos et accusato odio dignissimos ducimus qui blanditiis praesentium voluptatum.</p>-->
          </div>
      </div>
  </div>

  <!--=== Parallax Backgound ===-->
    <div class="bg-image-v2 bg-image-v2-dark parallaxBg1">
        <div class="container">
            <div class="headline-center-v2 margin-bottom-10">
                <!--<h2>Unify is a clean and fully responsive incredible template</h2>-->
                <span class="bordered-icon"><i class="fa fa-th-large"></i></span>
                <!--<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et qua s molestias excepturi vehicula sem ut volutpat. Ut non libero magna fusce co.</p><br><br>
                <button type="button" class="btn-u btn-brd btn-brd-hover btn-u-light">Download Now</button>-->
            </div><!--/Headline Center V2-->
        </div><!--/container-->
    </div>

<% end %>