config/routes.rb
Rails.application.routes.draw do

    root 'home#index'
      
    get 'password_resets/new'
  
    get 'password_resets/edit'
  
    get 'sessions/new'
  
    get 'users/new'

  
  
    get 'frequently_asked_questions' => 'static_pages#frequently_asked_questions'
  
  
    get 'about' =>  'static_pages#about'
    get 'jobs' =>  'static_pages#jobs'
    get 'community' =>  'static_pages#community'
    
    
    get 'doctor_job' => 'job_postings#doctor_job'
    get 'software_intern' => 'job_postings#software_intern'
    get 'web_dev' => 'job_postings#web_dev'
    
    get 'michael' => 'static_pages#michael'
    get 'francis' => 'static_pages#francis'
    get 'vance' => 'static_pages#vance'
    get 'thuan' => 'static_pages#thuan'
    
  
    get 'contact' => 'static_pages#contact'
  
    get 'help'    => 'static_pages#help'
  
    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    post 'pusher/auth'
   
    resources :users do
      member do
        post 'reactivate'
      end
      collection do
        get 'favorites'
      end
    end
    resources :doctors, only: :index do
      collection do
        get 'favorite'
      end
    end
    resources :sessions
    resources :video_sessions do
      member do
        get 'edit/feedback', to: 'video_sessions#feedback'
        get 'edit/notes', to: 'video_sessions#notes'
        patch 'finish', to: 'video_sessions#finish'
        patch 'update/feedback', to: 'video_sessions#update_feedback'
        patch 'update/notes', to: 'video_sessions#update_notes'
        patch 'update/add_diagnosis', to: 'video_sessions#add_diagnosis'
        patch 'update/sign_off', to: 'video_sessions#sign_off'
        patch 'update/save', to: 'video_sessions#save'
        get 'export'
        post 'transfer'
        post 'wait'

        resources :call_backs, only: [:new, :create]
        resources :online_visits, only: [:new, :create]
        resources :messages, only: [:new, :create]
        
      end
    end
    resources :call_backs, only: [:edit, :update, :destroy, :show, :create]
    
    resources :online_visits, only: [:edit, :update, :destroy, :show]
    resources :messages, only: [:show, :index, :update] do
      member do
        resources :answers, only: [:create]
      end
    end
    resources :photos, only: :create
    resources :history_video_sessions, only: [:index, :show]
    resources :clinics do
      collection do
        get 'favorite'
      end
    end
    resources :favorite_clinics, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :favorite_doctors, only: :create do
      collection do
        post 'remove'
      end
    end
    resources :appointments do
      member do
        post 'cancel'
      end
    end
    resources :not_working_dates, only: [:new, :create, :destroy]

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tasks
    resources :working_schedules, only: [:index]
    
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

    namespace :api do
      namespace :v1 do
        resources :users, only: [:create, :update] do
          collection do
            post 'sign_in' => 'sessions#create'
          end
        end
        resources :video_sessions do
          member do
            resource :opentok_session, only: :show
            post 'cancel'
          end
        end
        resources :appointments
        resources :clinics
        resources :doctors
        resources :messages
        resources :call_backs
      end
    end

end

app/models/video_session.rb
class VideoSession < ActiveRecord::Base
  validates_presence_of :symptom, :user_id
  belongs_to :user
  belongs_to :doctor, class_name: 'User'
  belongs_to :call_back
  has_many :photos
  has_one :opentok_session

  scope :pending, -> { where(status: :pending) }
  scope :started, -> { where(status: :started) }
  scope :waiting, -> { where(status: :waiting) }

  after_create :video_session_created
  after_update :video_session_updated

  def set_pending_timeout
    Delayed::Job.enqueue(PendingVideoSession.new(self.id), run_at: 15.minutes.from_now)
  end

  def video_session_updated
    if status_changed? and self.status == 'pending'
      set_pending_timeout
    end
  end

  def video_session_created
    if self.status == 'pending'
      set_pending_timeout
    end
  end
end

app/controllers/api/v1/video_sessions_controller.rb
class Api::V1::VideoSessionsController < Api::V1::AuthenticateController
  before_action :set_video_session, only: [:update, :show, :destroy]

  def create
    @video_session = VideoSession.new(video_session_params)
    if @video_session.save
      render json: @video_session
    else
      render json: @video_session.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def index
    @video_sessions = VideoSession.all
    render json: @video_sessions.order(created_at: :desc)
  end

  def show
    render json: @video_session
  end

  def update
    if @video_session.update(video_session_params)
      render json: @video_session
    else
      render json: @video_session.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def destroy
    @video_session.destroy
    render json: { result: 'success' }
  end

  private
  def video_session_params
    params.require(:video_session).permit(:user_id, :symptom, :doctor_id, :start_time, :finish_time, :status, :notes)
  end

  def set_video_session
    @video_session = VideoSession.find_by(id: params[:id])
    render json: { result: 'fail' } if @video_session.nil?
  end
end

app/controllers/video_sessions_controller.rb
require 'opentok'

class VideoSessionsController < AuthenticateController

  def new

  end
  
  def create
    if params[:online_visit].present?
      if current_user.csr?
        video_session = current_user.video_sessions.new(doctor_id: current_user.id, status: :online, symptom: 'Online Visit')
      else
        video_session = current_user.video_sessions.new(status: :pending, symptom: 'Online Visit')
      end
    else
      video_session = current_user.video_sessions.new(params.require(:video_session).permit(:symptom))
      video_session.status = :pending
    end
    
    if video_session.save
      flash.clear
      redirect_to video_session_path(video_session.id)
    else
      flash[:danger] = video_session.errors.full_messages.first
      render :new
    end
  end

  def index
    if current_user.doctor?
      @video_sessions = VideoSession.where("video_sessions.status = 'pending' OR video_sessions.status = 'waiting'").where.not(user_id: current_user.id)
                            .joins('LEFT JOIN call_backs ON call_backs.id = call_back_id')
                            .where('call_back_id IS NULL OR call_backs.doctor_id = ?', current_user.id)
                            .paginate(page: params[:scheduled_visit_page], per_page: 10)

      @call_backs = CallBack.all
      @tasks = Task.where(doctor_id: current_user.id).order(created_at: :desc)
    elsif current_user.csr?
      @video_sessions = VideoSession.pending.where.not(user_id: current_user.id)
                            .joins('LEFT JOIN call_backs ON call_backs.id = call_back_id')
                            .where('call_back_id IS NULL OR call_backs.doctor_id = ?', current_user.id)
                            .paginate(page: params[:scheduled_visit_page], per_page: 10)

      @call_backs = CallBack.all                            
    else
      @video_sessions = VideoSession.waiting.where(user_id: current_user.id)
                            .paginate(page: params[:scheduled_visit_page], per_page: 10)

      @call_backs = CallBack.where('call_backs.user_id = ?', current_user.id)
    end

    @call_backs = @call_backs.joins('LEFT JOIN video_sessions ON call_backs.id = video_sessions.call_back_id')
                       .where("video_sessions.status IS NULL OR (video_sessions.status <> 'finished' AND video_sessions.status <> 'callback')")

    @online_visits = OnlineVisit.where('online_visits.user_id = ? OR online_visits.csr_id = ?', current_user.id, current_user.id)
                       .joins('LEFT JOIN video_sessions ON online_visits.id = video_sessions.call_back_id')
                       .where("video_sessions.status IS NULL OR (video_sessions.status <> 'finished' AND video_sessions.status <> 'callback')")                       

  end

  def show
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session
      if @video_session.status == 'online'
        if current_user.csr?           
          redirect_to video_sessions_path and return if @video_session.doctor_id != current_user.id
          @is_csr = true
        else
          if @video_session.user_id == @video_session.doctor_id
            @video_session.update(user_id: current_user.id)
          else
            redirect_to video_sessions_path and return if @video_session.user_id != current_user.id
          end
        end
      else
        if current_user.csr? 
          if @video_session.status == 'pending'
            @video_session.update(status: :online, start_time: Time.zone.now, doctor_id: current_user.id)
            @is_csr = true
          else
            redirect_to video_sessions_path and return
          end
        else
          @is_doctor =  (@video_session.user_id != current_user.id and current_user.doctor?)
          if @is_doctor and (@video_session.status == 'pending' or @video_session.status == 'waiting')
            @video_session.status = :started
            @video_session.start_time = Time.zone.now
            @video_session.doctor_id = current_user.id
            @video_session.save
          end
          if @video_session.status != 'started' and @video_session.status != 'pending' and @video_session.status != 'online' and @video_session.status != 'waiting'
            redirect_to video_sessions_path and return
          end
          if @video_session.status == 'started' and @video_session.user_id != current_user.id and @video_session.doctor_id != current_user.id
            redirect_to video_sessions_path and return
          end
        end
      end

      try_count = 0
      while @token.blank? and try_count < 10
        begin
          if @video_session.opentok_session.try(:token).blank?
            opentok = OpenTok::OpenTok.new ENV['OPENTOK_API_KEY'], ENV['OPENTOK_SECRET']
            session = opentok.create_session :media_mode => :routed
            @token = session.generate_token
            @video_session.create_opentok_session(session_id: session.session_id, token: @token)
          elsif @video_session.opentok_session.updated_at < 24.hours.ago
            opentok = OpenTok::OpenTok.new ENV['OPENTOK_API_KEY'], ENV['OPENTOK_SECRET']
            session = opentok.create_session :media_mode => :routed
            @token = session.generate_token
            @video_session.opentok_session.update(session_id: session.session_id, token: @token)      
          end
          @token = @video_session.opentok_session.try(:token)
        rescue => e
          try_count += 1
        end
      end

      if @is_doctor
        set_s3_direct_post
        @photo = Photo.new
        @tasks = Task.where(doctor_id: current_user.id).order(created_at: :desc)
        @video_session.notes ||= "<strong>Subjective</strong>:<br><br><strong>Objective</strong>:<br><br><strong>Assessment</strong>:<br><br><strong>Plan</strong>:<br><br>"
      end
    end
  end

  def edit
    @video_session = current_user.video_sessions.find_by(id: params[:id])
  end

  def feedback
    @video_session = current_user.video_sessions.find_by(id: params[:id])
  end

  def notes
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end
  end

  def finish
    @video_session = VideoSession.find_by(id: params[:id])

    if @video_session and (@video_session.status == 'started' or @video_session.status == 'pending' or @video_session.status == 'online')
      if current_user.csr? and @video_session.doctor_id == current_user.id
        @video_session.finish_time = Time.zone.now
        @video_session.status = :finished
        @video_session.save
        redirect_to video_sessions_path
      else
        @is_doctor =  (@video_session.user_id != current_user.id)
        if @is_doctor
          @video_session.notes = params[:video_session][:notes]
          @video_session.finish_time = Time.zone.now
          @video_session.status = :finished
          @video_session.save
          redirect_to video_sessions_path
        else
          @video_session.finish_time = Time.zone.now
          @video_session.status = :finished
          @video_session.save
          render :feedback
        end
      end
    else
      redirect_to video_sessions_path
    end
  end

  def update_feedback
    @video_session = current_user.video_sessions.find_by(id: params[:id])
    @video_session.feedback = params[:video_session][:feedback]
    if @video_session.feedback.blank?
      flash[:danger] = "Feedback can't be blank"
      render :feedback
    elsif @video_session.save
      flash[:success] = "Submit feedback successfully"
      redirect_to root_path
    else
      flash[:danger] = @video_session.errors.full_messages.first
      render :feedback
    end
  end

  def update_notes
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end
    @video_session.notes = params[:video_session][:notes]
    if @video_session.notes.blank?
      flash[:danger] = "Notes can't be blank"
      render :notes
    elsif @video_session.save
      flash[:success] = "Write notes successfully"
      redirect_to video_sessions_path
    else
      flash[:danger] = @video_session.errors.full_messages.first
      render :notes
    end
  end

  def sign_off
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end
    @video_session.sign_off = true
    if @video_session.save
      render json: @video_session
    else
      render json: @video_session.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def add_diagnosis
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end
    @video_session.diagnosis = @video_session.diagnosis.to_s + params[:video_session][:diagnosis].to_s + '<br>'
    if @video_session.save
      render json: @video_session
    else
      render json: @video_session.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def save
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end
    @video_session.notes = params[:video_session][:notes]
    if @video_session.save
      Task.create(doctor_id: current_user.id, title: "Sign off on  #{@video_session.user.try(:name)}'s #{@video_session.created_at.strftime("%B %-d %I:%M %P")} Visit")
      render json: @video_session
    else
      render json: @video_session.errors.full_messages.first, status: :unprocessable_entity
    end
  end

  def export
    @video_session = VideoSession.find_by(id: params[:id])
    if @video_session.doctor_id != current_user.id
      redirect_to video_sessions_path
    end

app/views/video_sessions/_online_visit.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="online_visit_modal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="reg-header">Scheduled Online Visit</h4>
      </div>
      <div class="modal-body">
        <div class="field">
          <label>User</label><br>
          <div class="form-group" id='online_visit_user'></div>
        </div>
        <div class="field">
          <label id='online_visit_type'>Doctor</label><br>
          <div class="form-group" id='online_visit_doctor'></div>
        </div>
        <div class="field">
          <label>Scheduled Time</label><br>
          <div class="form-group" id='online_visit_scheduled_time'></div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" id='online_visit_start' class='btn btn-default'>
          <span class="glyphicon glyphicon-camera"></span> Start
        </a>
        <a href="#" id='online_visit_edit' class='btn btn-default'>
          <span class="glyphicon glyphicon-pencil"></span> Edit
        </a>
        <a href="#" id='online_visit_delete' class='btn btn-default' data-confirm='Are you sure?' data-method='delete'>
          <span class="glyphicon glyphicon-trash"></span> Delete
        </a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/video_sessions/_video_stream.html.erb
<div id="chat" data-api-key=<%= Pusher.key %> data-auth-endpoint=<%= pusher_auth_path %> ></div>
<div id="videos">
  <div id="remoteVideoContainer"></div>
  <div id="localVideoContainer"></div>
  <div class="dl dl-horizontal" id="messages"></div>
</div>

app/views/video_sessions/feedback.html.erb
<% provide(:title, "Thank You") %>
<h1>Thank You for using 24-7 Clinic!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <%= form_for(@video_session, url: update_feedback_video_session_path(@video_session)) do |f| %>
      <div class="form-group">
        <%= f.label 'Please rate us!' %>
      </div>
      <%= f.label :feedback %>
      <%= f.text_area :feedback, rows: 8, class: 'form-control' %>

      <%= f.submit 'Submit feedback', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/video_sessions/new.html.erb
<% provide(:title, "New Symptom") %>
<h1>New Symptom</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <%= form_for(:video_session, url: video_sessions_path) do |f| %>

      <%= f.label "Please indicate below with the symptoms that you're having and what kind of medical attention your require." %>
      <%= f.text_area :symptom, rows: 8, class: 'form-control' %>

      <div class="form-group">
        <%= f.submit 'Start Online Session', class: "btn btn-primary" %>
      </div>
      <div class="form-group">
        <input type="button" class="btn btn-primary start-chat-session" value="Start Chat Session with CSR">
      </div>
    <% end %>
  </div>
</div>

app/views/video_sessions/notes.html.erb
<% provide(:title, "Write Notes") %>
<h1>Write Notes</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <%= form_for(@video_session, url: update_notes_video_session_path(@video_session)) do |f| %>

      <%= f.label :notes %>
      <%= f.text_area :notes, rows: 8, class: 'form-control' %>

      <%= f.submit 'Submit notes', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/video_sessions/show.html.erb
<% if @is_csr %>
  <% provide(:title, "Online Visit") %>

  <div class="panel panel-profile no-bg">
    <div class="panel-heading overflow-h">
      <h2 class="panel-title heading-sm pull-left">Online Visit</h2>
    </div>

    <div class="panel-body">
      <div id="waiting-message"><h2>Waiting for Patient</h2></div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
          <div>
            <%= render 'video_stream' %>
          </div>
          <div class="form-group">
            <%= button_to 'Schedule Online Visit', new_online_visit_path(@video_session), method: :get, class: "btn btn-primary form-control" %>
          </div>
          <div class="form-group">
            <button class='btn btn-primary form-control btn-transfer-video-session-to-doctor' data-toggle="modal" data-target="#doctors_modal">Transfer Video Session to Doctor</button>
          </div>
          <div class="form-group">
            <button class="btn btn-primary form-control btn-put-wating" %>Put to Waiting Queue</button>
          </div>
          <%= form_for(@video_session, url: finish_video_session_path(@video_session)) do |f| %>
            <%= f.submit 'End Online Visit', id: "finish_video_session", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

      <div class="modal fade" id="doctors_modal" tabindex="-1" role="dialog" aria-labelledby="doctors_modal_title">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="doctors_modal_title">Transfer to Doctor</h4>
            </div>
            <div class="modal-body">
              <label>Select a doctor</label>
              <select class="form-control present-doctors"></select>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-info btn-chat" data-dismiss="modal">Chat</button>
              <button type="button" class="btn btn-primary btn-transfer">Transfer</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% elsif @is_doctor %>
  <% provide(:title, "Video Session with Patient") %>
  <div class="row">
    <div class="col-md-8 col-sm-8 col-xs-12">
      <div class="panel panel-profile no-bg">
        <div class="panel-heading overflow-h">
          <h2 class="panel-title heading-sm pull-left">Video Session with Patient</h2>
            <div class="btn-group pull-right" role="group" aria-label="...">
              <%= button_tag 'Sign-Off', class: "btn btn-default", id: "sign_off", disabled: @video_session.sign_off %>
              <%= button_tag 'Save & Exit', class: "btn btn-default", id: "save_exit" %> 
            </div>          
        </div>
        
        <div class="panel-body">
          <div id="waiting-message"><h2>Waiting for Patient</h2></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div>
                <%= render 'video_stream' %>
              </div>
              <div class="row form-group">
                <div class="col-md-12 col-sm-12 col-xs-12 center">
                  <div class="btn-group" role="group" aria-label="...">
                    <%= button_tag 'Take Photo', id: "take_photo", class: "btn btn-default" %> 
                    <%= button_tag 'End Session', id: "end_session", class: "btn btn-primary" %>
                    <%= button_tag 'Mute / Pause Session', id: "play_video_stream", class: "btn btn-default" %>
                  </div>
                </div>
              </div>
              <div class="form-group" id="taken_photos">

              </div>
              <canvas></canvas>
              <%= form_for(@photo, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
                <div class="field">
                  <%= f.label :photo_url %><br>
                  <%= f.file_field :photo_url %>
                  <%= f.submit %>
                </div>
              <% end %>
              <div class="row form-group">
                <div class="col-md-12 col-sm-12 col-xs-12 center">
                  <div class="btn-group" role="group" aria-label="...">
                    <%= button_tag 'Meds', class: "btn btn-default" %>
                    <%= button_tag 'LifeLabs', class: "btn btn-default" %> 
                    <%= link_to 'Pharmanent', 'https://jay.medinet.ca/cgi-bin/launch.cgi', class: "btn btn-default" %> 
                    <%= button_tag 'e-Fax', class: "btn btn-default" %> 
                    <%= button_tag 'Referrals', class: "btn btn-default" %> 
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%#= button_to 'Schedule Call Back', new_call_back_path(@video_session), method: :get, class: "btn btn-primary form-control" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
      <div class="panel panel-profile no-bg">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
              <h2 class="panel-title heading-sm pull-left">Notes</h2>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <div class="dropdown pull-right">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Export
                </button>
                <ul class="dropdown-menu export" aria-labelledby="dropdownMenu1">
                  <li id="export_print">Print</li>
                  <li>Fax</li>
                  <li id="export_file">File</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        
        <div class="panel-body">
          <%= form_for(@video_session, url: finish_video_session_path(@video_session)) do |f| %>
            <%#= f.label :notes %>
            <%= f.text_area :notes, rows: 13, class: 'form-control' %>

            <%= f.submit 'End Session', id: "finish_video_session", class: "btn btn-primary hidden" %>
          <% end %>
        </div>
      </div>
      <div class="panel panel-profile no-bg">
        <div class="panel-heading overflow-h">
          <h2 class="panel-title heading-sm pull-left">Billing</h2>
        </div>
        
        <div class="panel-body">
          <input class="form-control" id="video_session_diagnosis" placeholder="Add Diagnosis">
          <span class="video-session-diagnosis"><%= @video_session.diagnosis.to_s.html_safe.presence || 'Diagnosis here' %></span>
          <span class="pull-right">Billing Code here</span>
        </div>
      </div>
      <%= render 'tasks/tasks' %>
    </div>
  </div>
<% else %>
  <% title = @video_session.status == 'online' ? 'Online Visit' : 'Video Session' %>
  <% provide(:title, title) %>
  <div class="panel panel-profile no-bg">
    <div class="panel-heading overflow-h">
      <h2 class="panel-title heading-sm pull-left"><%= title %></h2>
    </div>
    
    <div class="panel-body">
      <div id="waiting-message"><h2>Waiting for Doctor</h2></div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
          <div>
            <%= render 'video_stream' %>
          </div>
          <div class="form-group">
            <%= button_to 'Schedule Online Appointment', call_backs_path(@video_session), method: :post, class: "btn btn-primary" %>
          </div>
          <div class="form-group">
            <%= button_to 'Leave Message', new_message_path(@video_session), method: :get, class: "btn btn-primary" %>
          </div>
          <div class="form-group">
            <%= button_to 'End Session', finish_video_session_path(@video_session), method: :patch, id: "finish_video_session", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  init_video_session(<%= current_user.id %>, "<%= current_user.name %>", <%= @video_session.id %>, <%= @video_session.user_id %>,
      "<%= ENV['OPENTOK_API_KEY'] %>", "<%= @video_session.opentok_session.session_id %>", "<%= @video_session.opentok_session.token %>", <%= @is_csr.present? %>);
</script>

app/views/video_sessions/view.html.erb
<% provide(:title, "Video Session") %>
<h1>Video Session</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <div class="form-group">
      <%= button_to 'Leave Callback', edit_callback_video_session_path(@video_session), method: :get, class: "btn btn-primary" %>
    </div>
    <div class="form-group">
      <%= button_to 'Leave Message', edit_message_video_session_path(@video_session), method: :get, class: "btn btn-primary" %>
    </div>
    <div class="form-group">
      <%= button_to 'End Session', edit_feedback_video_session_path(@video_session), method: :get, class: "btn btn-primary" %>
    </div>
  </div>
</div>